services:
  web:
    container_name: kajisuke-web
    build:
      context: .
    restart: always
    command: ["/app/entrypoint.sh"]
    volumes:
      - static_volume:/app/static
      - uwsgi_sock:/app/uwsgi.sock
    ports:
      - "3031:3031"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3031 || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s

  batch:
    container_name: kajisuke-batch
    build:
      context: .
    environment:
      - BATCH_ENABLED=false
    command: python manage.py runapscheduler
    restart: on-failure
    depends_on:
      - web
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f runapscheduler || exit 1"]
      interval: 30s
      retries: 3
      start_period: 20s

  nginx:
    image: nginx:latest
    container_name: kajisuke-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/static
      - uwsgi_sock:/app/uwsgi.sock
      - /var/log/kajisuke-nginx:/var/log/nginx
    depends_on:
      - web

volumes:
  static_volume:
  uwsgi_sock:
    driver: local
