services:
  web:
    container_name: kajisuke-web
    build:
      context: .
    restart: always
    command: ["/app/entrypoint.sh"]
    volumes:
      - static_volume:/app/static
      - uwsgi_sock:/app/uwsgi.sock
    ports:
      - "3031:3031"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3031 || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s
    
  nginx:
    image: nginx:latest
    container_name: kajisuke-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/static
      - uwsgi_sock:/app/uwsgi.sock
      - /home/ec2-user/nginx-logs:/var/log/nginx
    depends_on:
      - web

volumes:
  static_volume:
  uwsgi_sock:
    driver: local
