# Generated by Django 5.2 on 2025-05-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day_of_month',
        ),
    ]
